// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core'; <% if (useDefineFunction) { %>
import { define<%= name.endsWith('Component') ? name : `${name}Component` %> } from '<%= importPath %>';<% } else { %>
import { <%= name %> as <%= name %>CustomElement } from '<%= importPath %>';<% } %>
import { <%= name %> } from './<%= dasherize(baseName) %>.component';

@NgModule({
	imports: [CommonModule],
	declarations: [<%= name %>],
	exports: [<%= name %>]
})
export class <%= modulePrefix %><%= baseName %>Module {
	constructor() {
		<% if (useDefineFunction) {
			// Forge FloatingActionButton doesn't currently have Component suffix, but define function does.
			%>define<%= name.endsWith('Component') ? name : `${name}Component` %>();<%
		} else {
			%>if (!window.customElements.get('<%= tagName %>')) {
			window.customElements.define('<%= tagName %>', <%= name %>CustomElement);
		}<%
		} %>
	}
}