// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { <%= name %> } from './<%= dasherize(fileName) %>.component';

@NgModule({
	imports: [CommonModule],
	declarations: [<%= name %>],
	exports: [<%= name %>]
})
export class <%= name %>Module {}